const mongoose = require("mongoose");
const players = require("./models/players");
const Player = require("./models/players");

mongoose
  .connect("mongodb://localhost:27017/cricketscorekeeper")
  .then(() => {
    console.log("database connection successul");
  })
  .catch((e) => {
    console.log("Something went wrong with the database", e);
  });

const playerseed = ['Abhinav Mukund', 'Albie Morkel', 'Anirudha Srikkanth', 'Chamara Kapugedera', 'Jacob Oram', 'Joginder Sharma', 'KB Arun', 'Laksh pathy', 'Makhaya Ntini', 'Mahendra Singh', 'Manpreet Gony', 'Matthew Hayden', ' ke Hussey', 'Muttiah Muralitharan', 'Napoleon Einstein', 'Palani Amarnath', 'Parthiv Patel', 'Ravichandran Ashwin', 'Selvam Suresh', 'Shadab Jakati', 'Subramaniam Badrinath', 'Sudeep Tyagi', 'Suresh Raina', 'Vidyut Sivaramakrishnan', 'Viraj Kadbe', 'Adam Gilchrist', 'Andrew Symonds', 'Arjun Yadav', 'Chamara Silva', 'Do apaneni', 'Dwaraka Ravi', 'Herschelle Gibbs', 'Mohnish  shra', 'Nuwan Zoysa', 'Paidikalva Vijaykumar', 'PM Sarvesh', 'Pragyan Ojha', 'Sanjay Bangar', 'Shahid Afridi', 'Scott Styris', 'V.V.S. Laxman', 'Yalaka Venugopal', 'Brett Geeves', 'Daniel Vettori', 'Dinesh Karthik', 'Farveez Maharoof', 'Gautam Gambhir', 'Glenn McGrath', 'Manoj Tiwary', 'Mayank Tehlan', ' thun Manhas', 'Mohammad Asif', 'Pradeep Sangwan', 'Rajat Bhatia', 'Shikhar Dhawan',
  'Shoaib Malik', 'Tejashwi Yadav', 'Tillakaratne Dilshan', 'Virender Sehwag', 'Yogesh Nagar', 'Yo Mahesh', 'Aakash Chopra', 'Ajantha Mendis', 'Ajit Agarkar', 'Ashok Dinda', 'Brad Hodge', 'Brendon McCullum', 'Cheteshwar Pujara', 'Chris Gayle', 'David Hussey', 'Iqbal Abdulla', 'Ishant Sharma', 'Lax  Ratan', 'Mashrafe Mortaza', 'Mohammad Hafeez', 'Murali Kartik', 'Ranadeb Bose', 'Ricky Ponting', 'Rohan Banerjee', 'Salman Butt', 'Saurasish Lahiri', 'Shoaib Akhtar', 'Si arth', 'Sourav Ganguly', 'Tatenda Taibu', 'Wri himan', 'Yashpal Singh', 'Ajitesh Argal', 'Azhar Mehmood', 'Fidel Edwards', 'Gagandeep Singh', 'Irfan Pathan', 'James Hopes', 'Karan Goel', 'Kumar Sangakkara', 'Kyle  lls', 'Luke Pomersbach', 'Mahela Jayawardene', 'Nitin Saini', 'Pankaj Dharmani', 'Piyush Chawla', 'Ramesh Powar', 'Ramnaresh Sarwan', 'Rishi Dhawan', 'Sahil Kukreja', 'Shaun Marsh', 'Simon Katich', 'Sunny Sohal', 'Tanmay Srivastava', 'Uday Kaul', 'Wilkin Mota', 'Yuvraj Singh', 'Abhishek Nayar', 'Ajinkya Rahane', 'Ankeet Chavan', 'Ashwell Prince', 'Ashish Nehra', 'Dhawal Kulkarni', 'Dilhara Fernando', 'Dwayne Bravo', 'Gaurav Dhiman', 'Harbhajan Singh', 'Lasith Malinga', 'Loots Bosman', 'Luke Ronchi', 'Manish Pandey', 'Mohammad Ashraful', 'Musavir Khote', 'Pinal Shah', 'Rajesh Pawar', 'Robin Uthappa', 'Rohan Raje', 'Sachin Tendulkar', 'Sanath Jayasuriya', 'Saurabh Tiwary', 'Shaun Pollock', 'Si harth', 'Swapnil Singh', 'Vikrant Yeligati', 'Yogesh Takawale', 'Abdur Razzak', 'Anil Kumble', 'Ashley Noffke', 'Balachandra Akhil', 'Bharat Chipli', 'Cameron White', 'Dale Steyn', 'Devraj Patil', 'Jacques Kallis', 'Jagadeesh Arunkumar', 'KP Appanna', 'Mark Boucher', 'Nathan Bracken', 'Neravanda Aiyappa', 'Praveen Kumar', 'Rahul Dravid', 'Ross Taylor',
  'Shivnarine Chanderpaul', 'Shreevats Goswa', 'Sunil Joshi', 'Vinay Kumar', 'Virat Kohli', 'Wasim Jaffer', 'Zaheer Khan', 'Abhishek Raut', 'Aditya Angle', 'Anup Revandkar', 'Darren Lehmann', 'Dinesh Salunkhe', 'Faiz Fazal', 'Jaydev Shah', 'Justin Langer', 'Kamran Akmal', 'Mahesh Rawat', 'Mohammad Kaif', 'Morne Morkel', 'Munaf Patel', 'Niraj Patel', 'Pankaj Singh', 'Parag More', 'Ravindra Jadeja', 'Shane Warne', 'Si harth', 'Sohail Tanvir', 'Swapnil Asnodkar', 'Taruwar Kohli', 'Younis Khan', 'Yusuf Pathan', 'Andrew Flintoff', 'George Bailey', 'Murali Vijay', 'Thilan Thushara', 'Abhinav Kumar', 'Azhar Bilakhia', 'Harmeet Singh', 'Jaskaran Singh', 'Kemar Roach', 'Manvinder Bisla', ' tchell Marsh', 'Rahul Sharma', 'Ryan Harris', 'Shoaib Ahmed', 'Tirumalasetti Suman', 'Aavishkar Salvi', 'Andrew McDonald', 'David Warner', 'Dirk Nannes', 'Owais Shah', 'Paul Collingwood', 'Umesh Yadav', 'Wayne Parnell', 'Angelo Mathews', 'Anureet Singh', 'Arindam Ghosh', 'Charl Langeveldt', 'Moises Henriques', 'Sachin Rana', 'Shoaib Shaikh', 'Amanpreet Singh', 'Burt Cockley',
  'Jerome Taylor', 'Ravi Bopara', 'Ravikant Shukla', 'Rusty Theron', 'Ryan Ninan', 'Vikramjeet Malik', 'Yusuf Abdulla', 'Abu Nechim', 'Chentanya Nanda', 'Graham Napier', 'Rahil Shaikh', 'Ryan McLaren', 'Abhimanyu  thun', 'Bhuvneshwar Kumar', 'CM Gautam', 'Eoin Morgan', 'Ishank Jaggi', 'Jesse Ryder', 'Jitendra Patil', 'Karn Sharma', 'Kedar Jadhav', 'Kevin Pietersen', 'Rajesh Bishnoi', 'Raju Bhatkal', 'Rangaraj Suthesh', 'RK Sabharwal', 'Saurabh Bandekar', 'Sreenath Aravind', 'Tinu Yohannan', 'Udit Patel', 'Abdulahad Malek', 'Aditya Dole', 'Ashraf Makda', 'Atul Sharma', 'Gajendra Singh', 'Johan Botha', 'Kamran Khan', 'Lee Carseldine', 'Mohammed Arif', 'Naman Ojha', 'Paras Dogra', 'Paul Valthaty', 'Pushkaraj Chavan', 'Raiphi Gomez', 'Rob Quiney', 'Shaun Tait', 'Shrideep Mangela', 'Tyron Henderson', 'Chandrasekar Ganapathy', 'Doug Bollinger', 'Hemang Badani', 'Justin Kemp', 'Thisara Perera', 'Anirudh Singh', 'Bodapati Sumanth', 'Joginder Singh', 'Sarandeep Singh', 'Shashi Ranjan', 'Chirag Pathak', 'Ganapathi Vignesh', 'Harshad Khadiwale', 'Jaydev Unadkat', 'Mandeep Singh', 'Rohan Gavaskar', 'Shane Bond', 'Varun Aaron', 'Adrian Barath', 'Bipul Sharma', 'Love Ablish', 'Reetinder Singh', 'Shalabh Srivastava', 'Aditya Tare', 'Ali Murtaza', 'Ambati Rayudu', 'Chandan Madan', 'Ishan Malhotra', 'Kieron Pollard', 'Rahul Shukla', 'Rajagopal Sathish', 'Stuart Binny', 'Syed Shahabu', 'Sridharan Sriram', 'Aaron Finch', 'Abhishek Jhunjhunwala', 'Adam Voges', ' chael Lumb', 'Shrikant Wagh', 'Syed Quadri', 'Ben Hilfenhaus', 'Kuthethurshri Vasudevadas', 'Nuwan Kulasekara', 'Suraj Randiv', 'Tim Southee', 'Akash Bhandari', 'Anand Rajan', 'Ankit Sharma', 'Chris Lynn', 'Daniel Christian', 'Kedar Devdhar', 'Ajit Chandila', 'Colin Ingram', 'Matthew Wade',
  'Prashant Naik', 'Robbie Frylinck', 'Robin Bist', 'Shahbaz Nadeem', 'Travis Birt', 'Unmukt Chand', 'Vikas  shra', 'Vivek Yadav', 'James Pattinson', 'Deepak Chougule', 'John Hastings', ' chael Klinger', 'Padmanabhan Prasanth', 'Prasanth Parameswaran', 'Steve O Keefe', 'Sushant Marathe',
  'Bhargav Bhatt', 'David  ller', 'Manan Vohra', 'Stuart Broad', 'Sunny Singh', 'Aiden Blizzard', 'Clint McKay', 'Davy Jacobs', 'James Franklin', 'Pawan Suyal', 'Ray Price', 'Santosh Yadav', 'Sarul Kanwar', 'Suryakumar Yadav', 'Yuzvendra Chahal', 'Alfonso Thomas', 'Callum Ferguson', 'Dheeraj Jadhav', 'Eklavya Dwivedi', 'Ganesh Gaikwad', 'Harpreet Singh', 'Imtiaz Ahmed', 'James Faulkner', 'Nathan McCullum', 'Nayan Doshi', 'Shrikant Mundhe', 'Tim Paine', 'Abrar Kazi', 'Asad Pathan', 'BN Bharath', 'Jonathan Vandiar', 'Mayank Agarwal', 'Nuwan Pradeep', 'Rilee Rossouw', 'Syed Mohammed', 'Ashok Menaria', 'Deepak Chahar', 'Dishant Yagnik', 'Samad Fallah', 'Biplab Samantray', 'Daniel Harris', 'Darren Bravo', 'Sneha Kishore', 'Tanmay  shra', 'Tekka  Atchuta', 'TP Sudhindra', 'Veer Pratap', 'Andre Russell', 'Doug Bracewell', 'Glenn Maxwell', 'Gulam Bodi', 'Kuldeep Raval', 'Manpreet Juneja', 'Pawan Negi', 'Puneet Bisht', 'Sunny Gupta', 'Zafir Patel', 'Chirag Jani', 'Iresh Saxena', 'Sanju Samson', 'Sunil Narine', 'Ben Cutting', 'Gurkeerat Singh', 'Kyle Abbott', 'Parvinder Awana', 'A toze', 'Apoorv Wankhade', 'Kuldeep Yadav', ' tchell Johnson', 'Richard Levi', 'Robin Peterson', 'Sujit Nayak', 'Anustup Majumdar', 'Krishnakant Upadhyay', 'Luke Wright', 'Marlon Samuels', ' chael Clarke', 'Harshal Patel', 'Karun Nair', 'S.Thiagarajan', 'Brad Hogg', 'Dinesh Chandimal', 'Kevon Cooper', 'Samuel Badree', 'Akila Dananjaya', 'Ankit Rajpoot', 'Baba Aparajith', 'Ben Laughlin', 'Chris Morris',
  'Jason Holder', 'Mohit Sharma', 'R.Karthikeyan', 'Ronit More', 'Vijay Shankar', 'Arisht Singhvi', 'Ben Rohrer', 'Jeevan Mendis', 'Royston Dias', 'Sachithra Senanayake', 'Aniket Choudhary', ' chael Neser', 'Sandeep Sharma', 'Axar Patel', 'Jalaj Saxena', 'Jasprit Bumrah', 'Javed Khan', 'Nathan Coulter - Nile', 'Phillip Hughes', 'Ishwar Pandey', 'Kane Richardson', 'Parvez Rasool', 'Udit Birla', 'Chris Barnwell', 'KL Rahul', 'Ravi Rampaul', 'Sandeep Warrier', 'Sheldon Jackson', 'Kumar Boresa', 'Kusal Perera', 'Pravin Tambe', 'Sachin Baby', 'Darren Sammy', 'Hanuma Vihari', 'Thalaivan Sargunam', 'Matt Henry', 'HS Sharath', 'Imran Tahir', 'Jimmy Neesham', 'Jayant Yadav', ' lind Kumar', 'Sayan Mondal', 'Beuran Hendricks', 'Karanveer Singh', 'Shardul Thakur', 'Shivam Sharma', 'Ben Dunk', 'Corey Anderson', 'Josh Hazlewood', 'Krishmar Santokie', 'Lendl Simmons', 'Shreyas Gopal', ' tchell Starc', 'Ankush Bains', 'Deepak Hooda', 'Rahul Tewatia', 'Brendan Taylor', 'Chama  lind', 'Ricky Bhui', 'Pratyush Singh', 'Domnic Muthuswa', 'Gurinder Sandhu', 'KK Jiyas', 'Marcus Stoinis', 'Ravi Inder', 'Shreyas Iyer', 'Srikar Bharat', 'Travis Head', 'Aditya Garhwal', 'KC Cariappa', 'Vaibhav Rawal', 'Nikhil Naik', 'Yogesh Golwalkar', 'Gurinder Singh', 'Akshay Wakhare', 'Alex Hales', 'Colin Munro', 'Hardik Pandya', 'Jagadeesha Suchith', ' tchell McClenaghan', 'Nitish Rana', 'Roosh Kalaria', 'Si hesh', 'Adam  lne', 'David Wiese', 'Sarfaraz Khan', 'Sean Abbott', 'Shishir Bhavane', 'Barinder Sran', 'Pardeep Sahu', 'Sagar Trivedi', 'Kane Williamson', 'Trent Boult', 'Akhil Herwadkar', 'Kevin O Brien', 'Ben Cooper', 'Bilal Khan', 'Dawlat Zadran', 'Tendai Chatara', 'Callum McLeod', 'Carlos Brathwaite', 'Khaleel Ahmed', 'Mark Chapman', 'Rishabh Pant', 'Sam Billings', 'Akshdeep Nath', 'Ishan Kishan', 'Shivil Kaushik', 'Umang Sharma',
  'Sabbir Rahman', 'William Porterfield', 'Mudassar Bukhari', 'Johnson Charles', 'Mark Watt', 'Mohammad Shahzad', 'Richmond Mutumba', 'Nadeem Ahmed', 'Manan Sharma', 'George Dockrell', 'Tom Cooper', 'Sa ullah', 'Tinashe Panyangara', 'Babar Hayat', 'Alasdair Evans', 'Rangana Herath', 'Armaan Jaffer', 'Farhaan Behardien', 'Stephen Myburgh', 'Niall O Brien', 'Sikandar Raza', 'Gulbadin Naib', 'Preston Mommsen', 'Hashim Amla', 'Reece Topley', 'Deepak Punia', 'Jitesh Sharma', 'Mehran Khan', 'Tim Murtagh', 'Donald Tiripano', 'Usman Ghani', 'Anshuman Rath', 'Richie Berrington', 'Aaron Phangiso', 'Jos Buttler', 'Jefferey Vandersay', 'Kishore Kamath', 'Krunal Pandya', 'Martin Guptill', 'Nathu Singh', 'Akshay Karnewar', 'Chris Jordan', 'Joel Paris', 'Praveen Dubey', 'Tabraiz Shamsi',
  'Vikas Tokas', 'Mahmudullah Riyad', 'Wesley Barresi', 'Ed Joyce', 'Zeeshan Maqsood', 'Vusi Sibanda', 'Haseeb Amjad', 'Matt Machan', 'Adam Zampa', 'Murugan Ashwin', 'Peter Handscomb', 'Ajay Lalcheta', 'Josh Davey', 'Ha lton', 'Tanwir Afzal', ' linda Siriwardana', 'Scott Boland', 'Usman Khawaja', 'Andrew McBrine', 'Ahsan Malik', 'Munis Ansari', 'Andre Fletcher', 'Sean Williams', 'Nizakat Khan', 'Safyaan Sharif', 'Asghar Afghan', 'Dinesh Chandimal', 'Mustafizur Rahman', 'Ankit Bawne', 'Kagiso Rabada', 'Navdeep Saini', 'Shashank Singh', 'Ankit Soni', 'Basil Thampi', 'Chirag Suri', 'Pratham Singh', 'Rinku Singh', 'Shelley Shaurya', 'Shubham Agarwal', 'Tejas Baroka', 'Chris Woakes', 'Kinchit Shah', 'Rovman Powell', 'Sanjay Yadav', 'Sayan Ghosh', 'Shapoor Zadran', 'Sultan Ahmed[disambiguation', 'Boyd Rankin', 'Karim Sadiq',
  'Matthew Cross[disambiguation', 'Pietar Seelar', 'T Natarajan', 'Asela Gunaratne',
  'Krishnappa Gowtham', 'Kulwant Khejroliya', 'Max O Dowd', 'Nicholas Pooran', 'Najibullah Zadran', 'Avesh Khan', 'Billy Stanlake', 'Tymal  lls', 'Vishnu Vinod', 'Ben Stokes', 'Lockie Ferguson', ' lind Tandon', 'Rahul Chahar', 'Rahul Tripathi', 'Saurabh Kumar', 'Washington Sundar', 'Mohammad Nabi', 'Mohammed Siraj', 'Rashid Khan', 'Tanmay Agarwal', 'Chaitanya Bishnoi', 'David Willey', 'Dhruv Shorey', 'Kanishk Seth', 'KM Asif', 'Kshitiz Sharma', 'Lungi Ngidi', 'Mark Wood', ' tchell Santner', 'Monu Kumar', 'Narayan Jagadeesan', 'Abhishek Sharma', 'Junior Dala', 'Liam Plunkett', 'Manjot Kalra', 'Prithvi Shaw', 'Cameron Delport', 'Javon Searles', 'Kamlesh Nagarkoti', 'Prasidh Krishna', 'Shivam Mavi', 'Shubman Gill', 'Tom Curran', 'Ben Dwarshuis', 'Harvik Desai', 'Mayank Dagar', 'Umar Nazir', 'Evin Lewis', 'Jason Behrendorff', 'Mayank Markande', 'Mohsin Khan', 'Sharad Lumba', 'Tajinder Singh', 'Pavan Deshpande', 'Aryaman Birla', 'DArcy Short', 'Dushmantha Chameera', 'Heinrich Klaasen', 'Ish Sodhi', 'Jatin Saxena', 'Jofra Archer', 'Mahipal Lomror', 'Prashant Chopra', 'Sudhesan  dhun', 'Zahir Khan', 'Mehdi Hasan', 'Ruturaj Gaikwad', 'Scott Kuggeleijn', 'Bandaru Ayyappa', 'Keemo Paul', 'Sherfane Rutherford', 'Anrich Nortje', 'Harry Gurney', 'Joe Denly', 'Matthew Kelly', 'Agnivesh Ayachi', 'Arshdeep Singh', 'Darshan Nalkande', 'Hardus Viljoen', 'Harpreet Brar', 'Prabhsimran Singh', 'Sam Curran', 'Varun Chakravarthy', 'Alzarri Joseph', 'Anmolpreet Singh', 'Pankaj Jaiswal', 'Rasikh Salam', 'Ashton Turner', 'Liam Livingstone', 'Oshane Thomas', 'Riyan Parag', 'Shubham Ranjane', 'Devdutt Padikkal', 'Himmat Singh', 'Shimron Hetmyer', 'Shivam Dube', 'Jonny Bairstow', 'Karn Kaushal', 'R Vivek', 'Alex Carey', 'Daniel Sams', 'Lalit Yadav', 'Tushar Deshpande', 'Ali Khan', 'Chris Green', 'Tom Banton', 'Ishan Porel', 'Ravi Bishnoi', 'Sheldon Cottrell', 'Digvijay Deshmukh', 'Prince Balwant', 'Isuru Udana', 'Josh Philippe', 'Shahbaz Ahmed', 'Akash Singh', 'Anuj Rawat', 'Kartik Tyagi', 'Yashasvi Jaiswal', 'Abdul Samad', 'Bavanaka Sandeep', 'Fabian Allen', 'Priyam Garg', 'Virat Singh', 'Dawid Malan', 'Jhye Richardson', 'Rajat Patidar', 'Ripal Patel', 'Shahrukh Khan', 'Mohammed Azharu', 'Lukman Hussain',
  'Chetan Sakariya', 'Riley Meredith', 'Utkarsh Singh', 'Vaibhav Arora', 'Suyash Prabhudessai',
  'Kuldip Yadav', 'Yudhvir Charak', 'K.Bhagath', 'Chezhian Harinishanth', 'Marco Jansen', 'Venkatesh Iyer', 'Arjun Tendulkar', 'Finn Allen', 'Shams Mulani', 'Prerak Mankad',
  'Krishnan Shrijith', 'G Periyasamy', 'Gerald Coetzee', 'Josh Inglis', 'Haseeb Hameed', 'Nathan Ellis', 'Wanindu Hasaranga', 'Tim David', 'George Garton', 'Glenn Phillips', 'Jayden Seales', 'Akash Deep', 'Abhimanyu Easwaran', 'Umran Malik', 'Simarjeet Singh'];

const playerseedgenerator = (arr) => {
  let players = []
  for (let player of arr) {
    players.push({
      name: player
    })
  }
  return players
}

const seedData = async () => {
  const players = await Player.insertMany(playerseedgenerator(playerseed));
  console.log(players);
};

const clearSeed = async () => {
  await Player.deleteMany({});
};

const runseed = async () => {
  await clearSeed()
  await seedData()
}

runseed()
